<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_lngtxtfld</name>
   <tag></tag>
   <elementGuidId>e47accd9-0042-4a4e-a593-5a2eba114244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-2 > #lngtxtfld</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lngtxtfld']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf5b73f8-6a64-4fda-8e96-767d234a8ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c87-2 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>7120c481-601a-47f1-a536-e47ab0202496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d1c1fba3-72ef-4ccb-90dd-18aa18abfe4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lngtxtfld</value>
      <webElementGuid>6f5a3859-5949-4872-bfdc-dab9591c264c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1db5fee0-e8cf-4251-80d4-02fbcf880f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s4MainBody&quot;)/app-root[1]/app-login[1]/div[@class=&quot;s4-login-page mat-body-1&quot;]/div[@class=&quot;lgnbody&quot;]/div[@class=&quot;lgnbody-inner&quot;]/div[@class=&quot;logindiv&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[1]/div[1]/div[1]/s4-textbox[@id=&quot;lngtxtfld&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c99-0 ng-tns-c87-2 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-pristine ng-invalid ng-star-inserted mat-form-field-should-float mat-focused&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-2&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-2&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-2&quot;]/input[@id=&quot;lngtxtfld&quot;]</value>
      <webElementGuid>5d50a78c-7f64-49cd-9460-9ca75b8321ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lngtxtfld']</value>
      <webElementGuid>6945501e-4fc3-42c6-b3ad-ac2dfbe749d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-textbox[@id='lngtxtfld']/mat-form-field/div/div/div/input</value>
      <webElementGuid>87761474-a9df-47f2-8d2f-3fc08fe13d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5188a98a-c612-49f8-afd0-0e6d9c15ea76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lngtxtfld']</value>
      <webElementGuid>2af9a190-51db-42a9-914e-dcbfbce49b94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
