<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_lngpwdfld</name>
   <tag></tag>
   <elementGuidId>9438a8d2-7559-40e2-81c1-e5967a2b9848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-3 > #lngpwdfld</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lngpwdfld']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75b45e3c-2902-481a-899a-f2f902799ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>11e9f45a-bbb1-427f-8f55-3bdc5c0be2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>a4f3591c-6b04-459f-8d5e-4a767a77ec14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c87-3 ng-untouched cdk-text-field-autofill-monitored ng-dirty ng-valid</value>
      <webElementGuid>d45a52c3-7991-4855-b180-b29f1d4178d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lngpwdfld</value>
      <webElementGuid>fc3293ba-2fb0-4d26-a445-e9f6c9a83028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2ed00d36-2fd9-437c-82c2-0bc28f14cd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a70da8fc-7cd6-4b75-8b59-8e17de0a178c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s4MainBody&quot;)/app-root[1]/app-login[1]/div[@class=&quot;s4-login-page mat-body-1&quot;]/div[@class=&quot;lgnbody&quot;]/div[@class=&quot;lgnbody-inner&quot;]/div[@class=&quot;logindiv&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[2]/div[1]/div[1]/s4-password[@id=&quot;lngpwdfld&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c89-1 ng-tns-c87-3 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-star-inserted mat-form-field-should-float mat-focused ng-dirty ng-valid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-3&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-3&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-3&quot;]/input[@id=&quot;lngpwdfld&quot;]</value>
      <webElementGuid>65259732-95b0-4d63-864f-b886127a4429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lngpwdfld']</value>
      <webElementGuid>38d9b87f-3ced-4289-8d62-b8af0b4137f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-password[@id='lngpwdfld']/mat-form-field/div/div/div/input</value>
      <webElementGuid>9c97a094-4562-4a71-9bd0-e740efdaada7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//s4-password/mat-form-field/div/div/div/input</value>
      <webElementGuid>ba47cd04-ad5f-4317-a0d0-4617a0bc0180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'lngpwdfld']</value>
      <webElementGuid>77e68a50-e61d-42fe-8ca6-5babf5bf0e6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
