<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_menu</name>
   <tag></tag>
   <elementGuidId>e5db5da1-5db8-4a86-82d4-ad9091ccedb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.matIcon.material-icons.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='s4MainBody']/app-root/app-home/mat-toolbar/div/div/div/button/span/span/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>e985c0a8-d95e-4d78-ac9b-1357c8cd9d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a41f52d9-8123-43ad-ac71-567523ca67c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate matIcon material-icons mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>4a95af34-cb3b-4104-88e4-7b79124b194b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8598d548-6316-4ebe-b5cc-e1b4baad15ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>2a45b90c-ddb0-4c89-a3e5-e27afcaa8cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>28075050-871f-47da-9b14-c8625eab50d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s4MainBody&quot;)/app-root[1]/app-home[@class=&quot;ng-star-inserted&quot;]/mat-toolbar[@class=&quot;mat-toolbar s4-header mat-primary mat-toolbar-single-row&quot;]/div[@class=&quot;s4-header-center-align s4-toolbar&quot;]/div[@class=&quot;s4-header-center-align&quot;]/div[@class=&quot;s4-app-logo&quot;]/button[@class=&quot;mat-focus-indicator s4-sidenav-button mat-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/span[@class=&quot;drawer ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate matIcon material-icons mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>ca9ffc27-fe8b-4a1d-9e84-c9b1fa5b9916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='s4MainBody']/app-root/app-home/mat-toolbar/div/div/div/button/span/span/mat-icon</value>
      <webElementGuid>76f395bb-d9c2-4822-9a2f-f15fbf639130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elite 5.0 22:50'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>6e8d6739-0d32-4ead-b9fe-ff156db4d619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOBART RECEPTION PRISON'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>2a94e6ed-182a-4d93-91e2-79b689bf5eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='menu']/parent::*</value>
      <webElementGuid>071d3126-263b-4e08-a4da-a57512c37dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-icon</value>
      <webElementGuid>e4a74720-6a0e-4235-81fb-084da46bcac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'menu' or . = 'menu')]</value>
      <webElementGuid>ede46519-44f4-438a-9b01-bba9b638fc0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
