<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Case Note keyboard_arrow_down</name>
   <tag></tag>
   <elementGuidId>9601275e-c6ef-4a22-b00e-53d8e96cc33c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ag-cell-value.ag-cell.ag-cell-normal-height.ag-cell-not-inline-editing.ag-cell-focus.ag-cell-range-selected.ag-cell-range-selected-1.ag-cell-range-single-cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ag-grid-angular[@id='offnotestab']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0fed2977-6e0c-4c6a-aaf8-9e91aa44b969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>comp-id</name>
      <type>Main</type>
      <value>402</value>
      <webElementGuid>f1a09b23-91ed-4bdb-9538-53e7b57f4773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-cell-value ag-cell ag-cell-normal-height ag-cell-not-inline-editing ag-cell-focus ag-cell-range-selected ag-cell-range-selected-1 ag-cell-range-single-cell</value>
      <webElementGuid>c6f520de-aa57-4d3e-b05d-4f3ba2a38b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>34c69bfd-9353-4b3f-956d-715edb175981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8201333b-21f8-4ce9-b3ea-c26c340cf383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>col-id</name>
      <type>Main</type>
      <value>caseNoteType</value>
      <webElementGuid>bb0c3b24-9274-4869-b8bf-89cd7f112fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>a31fe9a7-35a7-46ee-9ba2-eadba4f904f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ea3f56f-c245-439e-96e6-0c52823c1678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Case Note keyboard_arrow_down</value>
      <webElementGuid>ad56d5ba-ee4e-4ba5-ae49-6b61245ec4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-8&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-102&quot;]/div[@class=&quot;ng-tns-c182-102&quot;]/div[1]/s4-grid[@id=&quot;offnotestab&quot;]/div[@id=&quot;gridContainer&quot;]/ag-grid-angular[@id=&quot;offnotestab&quot;]/div[@class=&quot;ag-root-wrapper ag-layout-auto-height ag-ltr&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-auto-height ag-focus-managed&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-auto-height&quot;]/div[@class=&quot;ag-body-viewport ag-layout-auto-height ag-row-animation ag-has-focus&quot;]/div[@class=&quot;ag-center-cols-clipper&quot;]/div[@class=&quot;ag-center-cols-viewport&quot;]/div[@class=&quot;ag-center-cols-container&quot;]/div[@class=&quot;ag-row-even ag-row ag-row-level-0 middle ag-row-position-absolute ag-row-first ag-row-last ag-row-selected ag-row-focus ag-row-hover ag-row-not-inline-editing&quot;]/div[@class=&quot;ag-cell-value ag-cell ag-cell-normal-height ag-cell-not-inline-editing ag-cell-focus ag-cell-range-selected ag-cell-range-selected-1 ag-cell-range-single-cell&quot;]</value>
      <webElementGuid>72c66cde-f3a3-438b-9153-62efb699e396</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ag-grid-angular[@id='offnotestab']/div/div[2]/div[2]/div[3]/div[2]/div/div/div/div[4]</value>
      <webElementGuid>12d41b31-c884-4e01-b959-8036bccc59f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institution'])[1]/following::div[2]</value>
      <webElementGuid>73aeba82-9ca9-430c-8331-ee72d13607d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amended'])[1]/following::div[22]</value>
      <webElementGuid>66ea4ecd-e367-4136-aefa-0b6543479d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DWIVEDI, ANJU'])[1]/preceding::div[10]</value>
      <webElementGuid>e3c97abc-0434-4b9f-89d7-a5b30b8e3c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div[4]</value>
      <webElementGuid>9c9bad70-cd05-4ab8-b22f-a6dc8becbdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Case Note keyboard_arrow_down' or . = ' Case Note keyboard_arrow_down')]</value>
      <webElementGuid>35b1508b-8ca5-4e7f-ad2f-024dcf624c65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
