<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dateADMISSION_DATE</name>
   <tag></tag>
   <elementGuidId>23333861-6846-41d7-af4f-773b5092a777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datepicker.ng-tns-c87-67 > #dateADMISSION_DATE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateADMISSION_DATE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6438544f-fdaa-419c-a39f-dd62452b8126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control mat-datepicker-input mat-tooltip-trigger ng-untouched ng-pristine cdk-text-field-autofill-monitored ng-invalid cdk-focused cdk-mouse-focused</value>
      <webElementGuid>63c413b0-52ce-4a14-b02a-55a12e5b8cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateADMISSION_DATE</value>
      <webElementGuid>ae68a7b1-3e0f-4f86-be88-b737197e1bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>867a029c-7dd5-468e-b95c-058a3358ec06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>a0a02846-bcc2-460d-98af-ab6cef4c0a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-calendar</name>
      <type>Main</type>
      <value>mat-datepicker-2</value>
      <webElementGuid>bbe15e4d-39e9-4715-9043-ac52f6914490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdk-describedby-host</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46e50236-179d-4098-bb1c-dd74d1c026c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-6&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-66&quot;]/div[@class=&quot;ng-tns-c182-66&quot;]/div[1]/s4-datepicker[@id=&quot;dateADMISSION_DATE&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c87-67 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-pristine ng-star-inserted ng-invalid mat-form-field-should-float mat-focused&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-67&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-67&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-67&quot;]/div[@class=&quot;datepicker ng-tns-c87-67&quot;]/input[@id=&quot;dateADMISSION_DATE&quot;]</value>
      <webElementGuid>8c14f2d5-a723-453e-992d-40a5c6807e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateADMISSION_DATE']</value>
      <webElementGuid>8ae0a5c2-de6b-46fd-9d5c-cec2d7e10087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-datepicker[@id='dateADMISSION_DATE']/mat-form-field/div/div/div/div/input</value>
      <webElementGuid>24adbceb-9a75-40cd-82a3-98384353b4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel/div/div/div/div/s4-datepicker/mat-form-field/div/div/div/div/input</value>
      <webElementGuid>0943799e-200d-4c6f-a4d5-84a87d7e610a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dateADMISSION_DATE']</value>
      <webElementGuid>587bc8dc-05d7-4a03-b3d5-ec94582392a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
