<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_lngpwdfld</name>
   <tag></tag>
   <elementGuidId>fe049cc1-d643-4998-898a-37f42ec3f8de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-3 > #lngpwdfld</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lngpwdfld']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc2ea29f-0ed1-40da-8c08-6b948a858d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>07d91d37-38db-4eca-a1ef-321eb5d5c40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>58c49cee-332e-405e-8c8b-85893b518f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c87-3 ng-untouched cdk-text-field-autofill-monitored ng-dirty ng-valid</value>
      <webElementGuid>fa131550-44ce-4fb3-8a20-b591be3342c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lngpwdfld</value>
      <webElementGuid>217b5251-d272-423f-8586-a199a5220735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>92421d0d-e9ae-4070-b502-88c3bc50e7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>15dc3c15-7ba7-4a08-b51c-80daf5f6d184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s4MainBody&quot;)/app-root[1]/app-login[1]/div[@class=&quot;s4-login-page mat-body-1&quot;]/div[@class=&quot;lgnbody&quot;]/div[@class=&quot;lgnbody-inner&quot;]/div[@class=&quot;logindiv&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[2]/div[1]/div[1]/s4-password[@id=&quot;lngpwdfld&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c89-1 ng-tns-c87-3 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-star-inserted mat-form-field-should-float mat-focused ng-dirty ng-valid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-3&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-3&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-3&quot;]/input[@id=&quot;lngpwdfld&quot;]</value>
      <webElementGuid>69458430-f345-4098-994c-818fffcf08e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lngpwdfld']</value>
      <webElementGuid>0c46fee3-8264-41f6-a91b-688cbf8c0e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-password[@id='lngpwdfld']/mat-form-field/div/div/div/input</value>
      <webElementGuid>85064066-b7f1-4d4c-96b2-68db02ad8b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//s4-password/mat-form-field/div/div/div/input</value>
      <webElementGuid>9edf4a1a-641a-49a0-a9dd-c30145919bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'lngpwdfld']</value>
      <webElementGuid>80bb423a-5459-4b72-8cb8-1aba6baa5384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
