<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_textnbt_first_name</name>
   <tag></tag>
   <elementGuidId>4f66807a-b668-4ca2-98d1-01a7a99d6bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-15 > #textnbt_first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textnbt_first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3beef19-8dc3-4454-87c4-66272c438a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c87-15 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored</value>
      <webElementGuid>ebcd02a0-19f8-4e9b-a800-53620b520b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>090b9ab8-3124-4a56-8988-b6f69c706446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textnbt_first_name</value>
      <webElementGuid>9562ece3-7bf5-4c01-a6ca-cec029c7d1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2110e543-7b83-4f7c-a089-c8dae9808dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1121c609-7145-4146-8a36-83129480fd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>3d273486-9722-4075-b6b0-b21e7a8fc504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-1&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-11&quot;]/form[@class=&quot;ng-tns-c182-11 ng-untouched ng-dirty ng-valid&quot;]/div[3]/div[1]/div[1]/div[1]/div[2]/s4-textbox[@id=&quot;textnbt_first_name&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c99-8 ng-tns-c87-15 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-15&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-15&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-15&quot;]/input[@id=&quot;textnbt_first_name&quot;]</value>
      <webElementGuid>834f94df-0b76-4285-8200-a08dec75c8ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textnbt_first_name']</value>
      <webElementGuid>5ece3ebc-af93-4db6-ad57-d2fa7d8d2fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-textbox[@id='textnbt_first_name']/mat-form-field/div/div/div/input</value>
      <webElementGuid>468ae81d-2194-4114-9f59-b5e1c8034b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/s4-textbox/mat-form-field/div/div/div/input</value>
      <webElementGuid>d4b6dbec-96d3-4dfb-ab81-c41f1f57044d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'textnbt_first_name']</value>
      <webElementGuid>1f3c1a85-0339-4653-9068-b0cb802da119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
