<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__textnbt_last_name</name>
   <tag></tag>
   <elementGuidId>898dca91-ba74-498e-ad6a-01930b1433e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-14 > #textnbt_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textnbt_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d496fbbb-5aeb-4b03-9f9e-bcb8c4aaf9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c87-14 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>6b4f39f5-afb3-42d7-8559-5849b85a8b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>177ec3e2-5924-498e-ac04-62c6eaa5d00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textnbt_last_name</value>
      <webElementGuid>a3357402-cc29-43a7-a292-1b85b0d5559b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc785f69-ec51-4bbd-a330-b977c45e0d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>fda7d0cf-197a-4b94-b407-fcb77b05755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-1&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-11&quot;]/form[@class=&quot;ng-tns-c182-11 ng-untouched ng-dirty ng-invalid&quot;]/div[3]/div[1]/div[1]/div[1]/div[1]/s4-textbox[@id=&quot;textnbt_last_name&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c99-7 ng-tns-c87-14 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-pristine ng-invalid ng-star-inserted mat-form-field-should-float mat-focused&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-14&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-14&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-14&quot;]/input[@id=&quot;textnbt_last_name&quot;]</value>
      <webElementGuid>bcc83453-d4bb-4abb-a9b4-fdb6a23a7731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textnbt_last_name']</value>
      <webElementGuid>dfefc526-2ba0-4522-b741-5a3ddee2f903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-textbox[@id='textnbt_last_name']/mat-form-field/div/div/div/input</value>
      <webElementGuid>9ec35f88-4ab2-432c-aca2-a1f3d1c5c330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field/div/div/div/input</value>
      <webElementGuid>5d7ca5c3-6caf-43aa-a6ba-d8038e3b5662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'textnbt_last_name']</value>
      <webElementGuid>bd9ea700-470a-4b15-90ec-63d9bf07bb7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
