<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_lngtxtfld</name>
   <tag></tag>
   <elementGuidId>dec7f043-de36-4124-8184-80f8c863f0d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-2 > #lngtxtfld</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lngtxtfld']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e33f382-60a2-4459-9c32-7e3bee3f57c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c87-2 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>3c27e1fc-a2b8-4d0f-a290-34eb38a588e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2f9c16d1-a07f-4bea-8e27-63fae0f0b39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lngtxtfld</value>
      <webElementGuid>787b3368-180a-4ada-9d90-5e3ceeedc1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>858c5a63-b95d-474f-b489-e1b77b89d924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s4MainBody&quot;)/app-root[1]/app-login[1]/div[@class=&quot;s4-login-page mat-body-1&quot;]/div[@class=&quot;lgnbody&quot;]/div[@class=&quot;lgnbody-inner&quot;]/div[@class=&quot;logindiv&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[1]/div[1]/div[1]/s4-textbox[@id=&quot;lngtxtfld&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c99-0 ng-tns-c87-2 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-pristine ng-invalid ng-star-inserted mat-form-field-should-float mat-focused&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-2&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-2&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-2&quot;]/input[@id=&quot;lngtxtfld&quot;]</value>
      <webElementGuid>f34403d9-449b-46bf-ab3c-dda918a0468b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lngtxtfld']</value>
      <webElementGuid>315d9726-c53d-4342-b721-174306d7d903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-textbox[@id='lngtxtfld']/mat-form-field/div/div/div/input</value>
      <webElementGuid>1affb2f7-4d8c-4157-a924-ace19a37cb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3b208325-ea63-432c-9eed-a6b45702689c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lngtxtfld']</value>
      <webElementGuid>3f488c71-f041-4d6b-ab75-73b18d1946d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
