<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_keyboard_arrow_down</name>
   <tag></tag>
   <elementGuidId>41413e0d-0ba1-4f57-b724-091027e5e130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c87-42 > div.lov-margin > mat-icon.mat-icon.notranslate.s4-material-icons.s4-menu-icon.material-icons.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//s4-lov[@id='selnbt_gender_code']/div/mat-form-field/div/div/div/div[2]/div[2]/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>ae0f59fd-2995-42e0-812d-c904f93d1b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6ef4090e-07e3-457b-a470-743b6486d45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate s4-material-icons s4-menu-icon material-icons mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>fb02a334-061f-4b8a-9189-03bdf0c7aa1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>81a67311-d274-4b20-bc73-6be9fefc20e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>e520cb22-af96-4324-babd-8dcacef9e662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>keyboard_arrow_down</value>
      <webElementGuid>a7448758-ef7a-4100-a837-a9eb545ac242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-2&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-33&quot;]/form[@class=&quot;ng-tns-c182-33 ng-untouched ng-valid ng-dirty&quot;]/div[1]/div[7]/s4-lov[@id=&quot;selnbt_gender_code&quot;]/div[@class=&quot;mat-body-1 s4-lov s4-lov-cdk&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c87-42 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-42&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-42&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-42&quot;]/div[@class=&quot;ng-tns-c87-42&quot;]/div[@class=&quot;lov-margin&quot;]/mat-icon[@class=&quot;mat-icon notranslate s4-material-icons s4-menu-icon material-icons mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>5b6287a1-6ada-4c3b-8b0f-a872aa13fe84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-lov[@id='selnbt_gender_code']/div/mat-form-field/div/div/div/div[2]/div[2]/mat-icon</value>
      <webElementGuid>09476f0b-83e4-46ba-83fb-89086cc6f28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::mat-icon[1]</value>
      <webElementGuid>8e55f3db-fb95-4ae4-bce8-ecf73bf43dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::mat-icon[2]</value>
      <webElementGuid>1bb38493-8c8b-422d-bf6b-d3bf11bc7df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Race'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>461ab966-fbbe-4b7c-b7fd-124b9f0450d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOB'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>1e5294a3-c24b-43e5-a189-9ffe86ab3381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/s4-lov/div/mat-form-field/div/div/div/div[2]/div[2]/mat-icon</value>
      <webElementGuid>bb6c3c2f-e721-4807-87f9-cd3c210c7107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'keyboard_arrow_down' or . = 'keyboard_arrow_down')]</value>
      <webElementGuid>98668726-2b3b-4441-adfe-3e2477b8a104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
