<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_menu</name>
   <tag></tag>
   <elementGuidId>cc2b0cf0-2e8f-4aab-8cfd-7c9534ec7d00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.matIcon.material-icons.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='s4MainBody']/app-root/app-home/mat-toolbar/div/div/div/button/span/span/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>7c61672b-7f63-4113-97e0-41790fd80ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>017624a3-cfb0-4657-9f5f-4a820e9563b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate matIcon material-icons mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>a1b56639-55c1-434b-9a1e-b5ca71e02ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c779d2c-31ad-42e3-9c11-1de616e77fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>52f51043-882c-439b-a721-5d829150e637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>9819533a-7048-4fa8-a9aa-1d5727863e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s4MainBody&quot;)/app-root[1]/app-home[@class=&quot;ng-star-inserted&quot;]/mat-toolbar[@class=&quot;mat-toolbar s4-header mat-primary mat-toolbar-single-row&quot;]/div[@class=&quot;s4-header-center-align s4-toolbar&quot;]/div[@class=&quot;s4-header-center-align&quot;]/div[@class=&quot;s4-app-logo&quot;]/button[@class=&quot;mat-focus-indicator s4-sidenav-button mat-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/span[@class=&quot;drawer ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate matIcon material-icons mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>1e27e82d-33ca-4791-8b88-38bfbac9c75f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='s4MainBody']/app-root/app-home/mat-toolbar/div/div/div/button/span/span/mat-icon</value>
      <webElementGuid>3d8bcf84-6349-41a7-bc7b-009d705d92bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elite 5.0 22:50'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>c5058653-6caf-4a9d-b6d4-58db1aff5c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOBART RECEPTION PRISON'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>0003eeb6-752c-4bb8-ac18-ddc2d681d0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='menu']/parent::*</value>
      <webElementGuid>839b5ab6-fc82-41c4-b758-c9d8eb3658f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-icon</value>
      <webElementGuid>25a8ebbb-24fc-4c54-926d-f4b1907bc3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'menu' or . = 'menu')]</value>
      <webElementGuid>788468fc-f2f2-4c26-b46f-9c0ad4bed869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
