<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Retrieve</name>
   <tag></tag>
   <elementGuidId>f2eafefc-8afb-4608-ae46-6640621933d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#retrbtn > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='retrbtn']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d9e8abbc-ad32-4f98-b977-fac9177f8f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>42869062-cebd-4fc7-b639-98cc02ad2df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Retrieve </value>
      <webElementGuid>0e679303-a0f4-47cb-a4cf-68ea608caea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-1&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-11&quot;]/form[@class=&quot;ng-tns-c182-11 ng-dirty ng-valid ng-touched&quot;]/div[4]/div[@class=&quot;group-btns&quot;]/div[1]/span[2]/s4-button[@id=&quot;retrbtn&quot;]/button[@id=&quot;retrbtn&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>1728850f-7115-4817-af1d-f5357157e9da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='retrbtn']/span</value>
      <webElementGuid>280f285a-7693-4615-afcd-9faac483ba91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retrieve'])[1]/following::span[4]</value>
      <webElementGuid>ba052def-6bb1-4019-8ebe-8909e7e4ef90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::span[3]</value>
      <webElementGuid>c29366c7-8868-4021-b3a4-f73214c1d5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Offender Record'])[1]/preceding::span[6]</value>
      <webElementGuid>450ec1fc-b1c3-47eb-aef5-ddd1ffb2b3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/s4-button/button/span</value>
      <webElementGuid>cda23d10-1212-4424-ac76-2500bdbeda0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Retrieve ' or . = ' Retrieve ')]</value>
      <webElementGuid>c65580b0-c59c-4e87-aad1-3128e7832648</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
