<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save</name>
   <tag></tag>
   <elementGuidId>eeb50ef7-f6a4-470e-b4e3-a621a8f64448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#butsave > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='butsave']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4a5f3913-ef41-4fb5-83f9-0b299d4cf2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>4060e3fb-4c79-440d-bf72-c8d53f90f5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save </value>
      <webElementGuid>797fcde0-a9bd-4fc0-b3d1-43f8a0901970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-7&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-82&quot;]/div[@class=&quot;btn-mt9 ng-tns-c182-82&quot;]/s4-button[@id=&quot;butsave&quot;]/button[@id=&quot;butsave&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>4723cd87-fd5f-4699-9014-7fb2abb8e911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='butsave']/span</value>
      <webElementGuid>25d2d334-5864-4d6c-8b85-171e9c97ed9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Housing Unit'])[1]/following::span[3]</value>
      <webElementGuid>c6936f26-2151-4520-a51e-8c2624bc1abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/following::span[6]</value>
      <webElementGuid>6b3439d4-0b5f-4dac-807c-754c1bca7f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[2]/preceding::span[3]</value>
      <webElementGuid>4bc87b46-fa6b-44eb-83dc-5542b9b014d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Existing Bookings'])[1]/preceding::span[6]</value>
      <webElementGuid>68c6c787-50d9-495f-9c3b-8d738214135b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>148ec39a-05b5-4822-8fae-2b98e62cc095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/s4-button/button/span</value>
      <webElementGuid>76bccae7-b4b6-4c7a-b36e-3b01c1e24cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Save ' or . = ' Save ')]</value>
      <webElementGuid>e91810fc-8da5-41dd-adc8-3bd53b893f86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
