<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__textcasenotetext</name>
   <tag></tag>
   <elementGuidId>6898700f-aedf-4f6e-9b83-0ace84b0a038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-123 > #textcasenotetext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textcasenotetext']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6d73b09c-e72a-4ed3-addf-e5aeebf4122b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c87-123 ng-untouched cdk-text-field-autofill-monitored ng-dirty ng-valid</value>
      <webElementGuid>5d1f2fac-9714-4b7a-a847-2d52620f610e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>487b6d05-e9bb-477e-b3bd-280e5cc15819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textcasenotetext</value>
      <webElementGuid>35fb42be-786d-4cd6-8a03-b152592cfad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>23df12db-1d85-4fae-a4df-00bec028bafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32000</value>
      <webElementGuid>4319fcb8-739a-4372-bc7e-54bb51227f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd558904-dbdb-4d17-95cd-8606b5869b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-8&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c182-102&quot;]/div[@class=&quot;ng-tns-c182-102&quot;]/div[1]/s4-textarea[@id=&quot;textcasenotetext&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c87-123 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-star-inserted mat-form-field-should-float mat-focused ng-dirty ng-valid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-123&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-123&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-123&quot;]/textarea[@id=&quot;textcasenotetext&quot;]</value>
      <webElementGuid>2d08a259-a031-42c5-9a4a-7ed8bb863828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textcasenotetext']</value>
      <webElementGuid>7bf389ff-2a37-4510-a812-395c83f42e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-textarea[@id='textcasenotetext']/mat-form-field/div/div/div/textarea</value>
      <webElementGuid>e75aa415-6037-471f-aa44-7d8be7124a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::textarea[1]</value>
      <webElementGuid>58ebaece-524c-440e-9f2d-5f3647f6dfdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Notes'])[4]/following::textarea[1]</value>
      <webElementGuid>bda9698b-442b-41f3-b695-263e00b4bbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>828646d7-6585-418b-b02c-6188aa7830d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textcasenotetext']</value>
      <webElementGuid>8d3c9913-2e78-4bc3-8b07-7e71c925b9ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
