<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_lngpwdfld</name>
   <tag></tag>
   <elementGuidId>6ac58955-276c-44de-b46c-66114bcf04ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-3 > #lngpwdfld</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lngpwdfld']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>495172d0-5e46-4f8d-8d0e-9a4715f07c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>725a863e-0ba5-4f57-8044-434d3cc17d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>ef8b1274-21b9-452d-a2a9-20811bfd0a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c87-3 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>9f994adf-d14d-447e-9c9e-707bcd08a0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lngpwdfld</value>
      <webElementGuid>bffbc53c-e9d2-4011-a266-9e99965aa45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6fcc7913-b701-462d-af9a-1849dfdb04e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s4MainBody&quot;)/app-root[1]/app-login[1]/div[@class=&quot;s4-login-page mat-body-1&quot;]/div[@class=&quot;lgnbody&quot;]/div[@class=&quot;lgnbody-inner&quot;]/div[@class=&quot;logindiv&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[2]/div[1]/div[1]/s4-password[@id=&quot;lngpwdfld&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c89-1 ng-tns-c87-3 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-3&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-3&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-3&quot;]/input[@id=&quot;lngpwdfld&quot;]</value>
      <webElementGuid>85279743-4c36-4abb-94ac-6ec020f6b294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lngpwdfld']</value>
      <webElementGuid>0f79f80b-64fd-4567-920e-c40b61c0a185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-password[@id='lngpwdfld']/mat-form-field/div/div/div/input</value>
      <webElementGuid>e36db3e5-4c80-4d99-ab6e-564fc8c0dfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//s4-password/mat-form-field/div/div/div/input</value>
      <webElementGuid>55bde9fb-80b9-4a49-9fb9-ae036a16aa54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'lngpwdfld']</value>
      <webElementGuid>4b6975bc-0859-4e9b-8fde-e864998c0488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
