<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name is required_lngtxtfld</name>
   <tag></tag>
   <elementGuidId>2b24b4ac-ecbc-4c86-8f75-4e0d81708451</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-2 > #lngtxtfld</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lngtxtfld']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5bf4d25-ba5d-4388-82a4-a9755ee85bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c87-2 ng-pristine ng-invalid cdk-text-field-autofill-monitored ng-touched</value>
      <webElementGuid>535e2296-a8ac-4ffe-90df-34ed2e9f9395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b64b5e14-440b-4a9d-b204-7aaf7b6a6a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lngtxtfld</value>
      <webElementGuid>e4ee7d69-d764-4dae-89ea-ae23fda41efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a00a762-aba8-4727-abf0-7abc315d0ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-error-0</value>
      <webElementGuid>69397c47-d53b-4bed-b81c-51828b94992a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s4MainBody&quot;)/app-root[1]/app-login[1]/div[@class=&quot;s4-login-page mat-body-1&quot;]/div[@class=&quot;lgnbody&quot;]/div[@class=&quot;lgnbody-inner&quot;]/div[@class=&quot;logindiv&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[1]/div[1]/div[1]/s4-textbox[@id=&quot;lngtxtfld&quot;]/mat-form-field[@class=&quot;mat-form-field component-full-width ng-tns-c99-0 ng-tns-c87-2 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-hide-placeholder ng-pristine ng-invalid ng-star-inserted mat-form-field-invalid ng-touched mat-form-field-should-float mat-focused&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-2&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-2&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-2&quot;]/input[@id=&quot;lngtxtfld&quot;]</value>
      <webElementGuid>6e19544f-9646-4d72-90e9-bb900f467cce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lngtxtfld']</value>
      <webElementGuid>99bdbfe2-1107-4431-b66c-d7f880ce8fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//s4-textbox[@id='lngtxtfld']/mat-form-field/div/div/div/input</value>
      <webElementGuid>e70a288a-1879-4fbe-9a0f-0db4ff88f12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>99f817e4-f421-420e-8dd2-f7116e9c31f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lngtxtfld']</value>
      <webElementGuid>a0230e9d-70ba-4644-817c-db2c965dd97f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
